/**
 * Bakes the fonts and placeholder photos into source as base64.
 *
 * The poster is opened from disk, where `fetch()` of a neighbouring file is blocked and a
 * cross-origin asset taints the export canvas. Every asset the page needs by default has to be
 * inside the HTML itself, so this runs before dev and build rather than leaving Vite to decide
 * what is small enough to inline.
 */
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

const ROOT = join(import.meta.dirname, '..')
const FONT_DIR = join(ROOT, 'assets', 'fonts')
const IMAGE_DIR = join(ROOT, 'assets', 'images')
const OUT_DIR = join(ROOT, 'src', 'lib', 'generated')

const BANNER = '/* Generated by scripts/inline-assets.ts — do not edit by hand. */\n'

const base64 = async (path: string): Promise<string> => (await readFile(path)).toString('base64')

async function buildFonts(): Promise<number> {
  const css = await readFile(join(FONT_DIR, 'fonts.css'), 'utf8')
  const files = (await readdir(FONT_DIR)).filter((f) => f.endsWith('.woff2'))

  let inlined = css
  for (const file of files) {
    const uri = `data:font/woff2;base64,${await base64(join(FONT_DIR, file))}`
    inlined = inlined.replaceAll(`url(./${file})`, `url(${uri})`)
  }

  const missed = inlined.match(/url\((?!data:)[^)]*\)/g)
  if (missed) throw new Error(`Font file not inlined: ${missed.join(', ')}`)

  await writeFile(join(OUT_DIR, 'fonts.css'), BANNER + inlined, 'utf8')
  return inlined.length
}

async function buildImages(): Promise<number> {
  const entries = await Promise.all(
    ['placeholder-left.png', 'placeholder-right.png'].map(async (file) => {
      const name = file.replace('.png', '').replace(/-(\w)/g, (_, c: string) => c.toUpperCase())
      return `export const ${name} = 'data:image/png;base64,${await base64(join(IMAGE_DIR, file))}'\n`
    }),
  )

  const body = BANNER + '\n' + entries.join('\n')
  await writeFile(join(OUT_DIR, 'placeholders.ts'), body, 'utf8')
  return body.length
}

await mkdir(OUT_DIR, { recursive: true })
const [fonts, images] = await Promise.all([buildFonts(), buildImages()])
console.log(
  `Inlined fonts (${Math.round(fonts / 1024)}KB) and placeholders (${Math.round(images / 1024)}KB)`,
)
